import { useEffect, useState } from 'react';
import { getAIHealth, investigateChange, listChanges } from '../services/api';
import type { Change } from '../types/change';
import type { Investigation } from '../types/investigation';

export function InvestigationPage() {
  const [changes, setChanges] = useState<Change[]>([]); const [selectedId, setSelectedId] = useState(''); const [investigation, setInvestigation] = useState<Investigation | null>(null); const [provider, setProvider] = useState<{ available: boolean; message: string } | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { void Promise.all([listChanges({ limit: 100 }), getAIHealth()]).then(([changeResult, health]) => { setChanges(changeResult.data); setProvider(health); if (changeResult.data[0]) setSelectedId(changeResult.data[0].id); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load investigation context.')).finally(() => setLoading(false)); }, []);
  async function investigate() { setBusy(true); setError(null); try { setInvestigation(await investigateChange(selectedId)); setNotice('AI investigation completed.'); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'AI investigation failed.'); } finally { setBusy(false); } }
  const selected = changes.find((change) => change.id === selectedId);
  return <section className="investigation-section" id="investigation" aria-labelledby="investigation-title"><div className="investigation-heading"><div><p className="eyebrow">Phase 7 · Evidence-backed AI</p><h2 id="investigation-title">Investigation and RCA</h2><p className="section-copy">AI reasoning is advisory and evidence-backed. Deterministic ChangeLens facts remain authoritative.</p></div></div>{loading ? <p className="empty-state">Loading investigation context...</p> : changes.length === 0 ? <p className="empty-state">No changes are available to investigate.</p> : <><div className="investigation-toolbar"><label>Change<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{changes.map((change) => <option key={change.id} value={change.id}>{change.summary}</option>)}</select></label><button className="button button--primary" disabled={busy} type="button" onClick={() => void investigate()}>{busy ? 'Investigating...' : 'Investigate with AI'}</button></div>{provider && !provider.available ? <p className="provider-warning" role="status">{provider.message}. The API remains healthy; investigation is unavailable.</p> : null}{error ? <div className="inline-error" role="alert"><span>{error}</span><button className="text-button" type="button" onClick={() => setError(null)}>Dismiss</button></div> : null}{notice ? <p className="success-message" role="status">{notice}</p> : null}{selected ? <div className="change-context"><strong>{selected.summary}</strong><span>{selected.changeType} · {selected.source} · Resource {selected.resourceId}</span></div> : null}{investigation ? <InvestigationDetail item={investigation} /> : <p className="empty-state">Run an investigation to generate evidence-backed reasoning.</p>}</>}</section>;
}

function refs(ids: string[]) { return ids.length ? ids.map((id) => <a key={id} href="#evidence">{id}</a>) : <span>None</span>; }
function InvestigationDetail({ item }: { item: Investigation }) { if (item.status === 'failed') return <article className="ai-card ai-card--error"><h3>Investigation failed</h3><p>{item.errorMessage ?? 'AI investigation unavailable.'}</p></article>; return <div className="investigation-detail"><p className="ai-label">AI-GENERATED REASONING · {item.provider} / {item.model}</p><article className="ai-card"><h3>Summary</h3><p>{item.summary}</p><h3>Root cause</h3><p>{item.rootCause?.statement ?? 'Insufficient evidence to determine root cause.'}</p><p>Confidence: {item.rootCause?.confidence ?? 0}% · Evidence: {refs(item.rootCause?.evidenceIds ?? [])}</p></article><div className="ai-grid"><article className="ai-card"><h3>Reasoning</h3>{item.reasoning.map((entry, index) => <p key={`${entry.type}-${index}`}><strong>{entry.type}:</strong> {entry.statement}</p>)}</article><article className="ai-card"><h3>Hypotheses</h3>{item.hypotheses.length ? item.hypotheses.map((hypothesis) => <div className="ai-item" key={hypothesis.title}><strong>{hypothesis.title}</strong><p>{hypothesis.explanation}</p><small>Confidence {hypothesis.confidence}% · Supporting: {refs(hypothesis.supportingEvidenceIds)}</small></div>) : <p>None generated.</p>}</article><article className="ai-card"><h3>Impact and prediction reality</h3><p>{item.impactExplanation}</p><p>{item.predictionRealityExplanation}</p></article><article className="ai-card"><h3>Recommendations</h3>{item.recommendations.length ? item.recommendations.map((recommendation) => <div className="ai-item" key={recommendation.title}><strong>{recommendation.title}</strong><p>{recommendation.explanation}</p><small>{recommendation.safe ? 'Advisory' : 'Human approval required'} · Evidence: {refs(recommendation.supportingEvidenceIds)}</small></div>) : <p>None generated.</p>}</article></div><article className="ai-card"><h3>Limitations</h3>{item.limitations.map((limitation) => <p key={limitation}>{limitation}</p>)}</article></div>; }