import { useEffect, useState } from 'react';
import { comparePrediction, createObservation, createPrediction, getComparison, getPrediction, listChanges, listObservations } from '../services/api';
import type { Change } from '../types/change';
import type { ObservedImpact, PredictionComparison, PredictionSnapshot } from '../types/predictionReality';

function isoInput(date: Date): string { return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }

export function PredictionRealityPage() {
  const [changes, setChanges] = useState<Change[]>([]); const [selectedId, setSelectedId] = useState(''); const [prediction, setPrediction] = useState<PredictionSnapshot | null>(null); const [observation, setObservation] = useState<ObservedImpact | null>(null); const [comparison, setComparison] = useState<PredictionComparison | null>(null); const [start, setStart] = useState(isoInput(new Date(Date.now() - 60 * 60 * 1000))); const [end, setEnd] = useState(isoInput(new Date())); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { void listChanges({ limit: 100 }).then((result) => { setChanges(result.data); if (result.data[0]) setSelectedId(result.data[0].id); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load changes.')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selectedId) return; setPrediction(null); setObservation(null); setComparison(null); void getPrediction(selectedId).then(setPrediction).catch(() => undefined); }, [selectedId]);
  async function run(action: () => Promise<void>, success: string) { setBusy(true); setError(null); try { await action(); setNotice(success); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : 'Prediction vs Reality request failed.'); } finally { setBusy(false); } }
  const selected = changes.find((item) => item.id === selectedId);
  return <section className="reality-section" id="prediction-reality" aria-labelledby="prediction-reality-title"><div className="reality-heading"><div><p className="eyebrow">Phase 6 · Feedback loop</p><h2 id="prediction-reality-title">Prediction vs Reality</h2><p className="section-copy">Compare deterministic predictions with structured evidence. Missing evidence remains inconclusive; it is never treated as proof of no impact.</p></div></div>{loading ? <p className="empty-state">Loading changes...</p> : changes.length === 0 ? <p className="empty-state">No changes are available for comparison.</p> : <><div className="reality-toolbar"><label>Change<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{changes.map((change) => <option key={change.id} value={change.id}>{change.summary}</option>)}</select></label><button className="button button--primary" disabled={busy} type="button" onClick={() => void run(async () => { setPrediction(await createPrediction(selectedId)); setObservation(null); setComparison(null); }, 'Prediction snapshot created.')}>Create prediction</button></div>{selected ? <div className="change-context"><strong>{selected.summary}</strong><span>{selected.changeType} · {selected.source} · Resource {selected.resourceId}</span></div> : null}{error ? <div className="inline-error" role="alert"><span>{error}</span><button className="text-button" type="button" onClick={() => setError(null)}>Dismiss</button></div> : null}{notice ? <p className="success-message" role="status">{notice}</p> : null}{prediction ? <PredictionPanel prediction={prediction} /> : <p className="empty-state">Create a prediction snapshot from the latest Change Intelligence analysis.</p>}{prediction ? <div className="reality-actions"><label>Window start<input type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>Window end<input type="datetime-local" value={end} onChange={(event) => setEnd(event.target.value)} /></label><button className="button button--primary" disabled={busy} type="button" onClick={() => void run(async () => { setObservation(await createObservation(selectedId, { predictionId: prediction.id, start: new Date(start).toISOString(), end: new Date(end).toISOString() })); setComparison(null); }, 'Evidence observation created.')}>Observe evidence</button><button className="button button--quiet" disabled={busy || !observation} type="button" onClick={() => void run(async () => { setComparison(await comparePrediction(selectedId, { predictionId: prediction.id, observationId: observation!.id })); }, 'Prediction compared with reality.')}>Compare</button></div> : null}{observation ? <ObservationPanel observation={observation} /> : null}{comparison ? <ComparisonPanel comparison={comparison} /> : null}</>}</section>;
}

function PredictionPanel({ prediction }: { prediction: PredictionSnapshot }) { return <article className="reality-card"><h3>Predicted</h3><div className="reality-stats"><strong>{prediction.predictedRisk.score} <small>{prediction.predictedRisk.level}</small></strong><span>Impact: {prediction.predictedImpact.categories.join(', ') || 'None derived'}</span><span>Resources: {prediction.predictedResourceIds.length}</span><span>Blast radius: {prediction.predictedBlastRadius.totalCount}</span></div><p>{prediction.predictedImpact.summary}</p></article>; }
function ObservationPanel({ observation }: { observation: ObservedImpact }) { return <article className="reality-card reality-card--observed"><h3>Observed</h3><p className="evidence-state">{observation.status === 'insufficient_evidence' ? 'INSUFFICIENT EVIDENCE' : 'SUPPORTED BY AVAILABLE EVIDENCE'}</p><p>{observation.observedImpact.summary}</p><p>Categories: {observation.observedImpact.categories.join(', ') || 'Not determined'}</p><p>Resources: {observation.observedResources.join(', ') || 'Not determined'}</p>{observation.observedMetrics.length > 0 ? <div>{observation.observedMetrics.map((metric) => <p key={metric.name}>{metric.name}: {metric.baseline} → {metric.observed} ({metric.direction}, delta {metric.delta})</p>)}</div> : <p>Metrics: Not supported by available evidence.</p>}</article>; }
function ComparisonPanel({ comparison }: { comparison: PredictionComparison }) { return <article className="reality-card reality-card--comparison"><h3>Comparison and accuracy</h3><div className="reality-stats"><strong>{comparison.accuracy.score ?? '—'} <small>{comparison.accuracy.level}</small></strong><span>Confirmed: {comparison.impactComparison.confirmedCategories.join(', ') || 'None'}</span><span>Not confirmed: {comparison.impactComparison.unconfirmedCategories.join(', ') || 'None'}</span><span>Unexpected: {comparison.impactComparison.unexpectedCategories.join(', ') || 'None'}</span></div><p>{comparison.summary}</p><p>Security: {comparison.securityComparison.status}; confirmed {comparison.securityComparison.confirmed.length}; unexpected {comparison.securityComparison.unexpected.length}.</p><p>Blast radius: predicted {comparison.blastRadiusComparison.predictedTotal}; observed {comparison.blastRadiusComparison.observedTotal ?? 'unknown'}; delta {comparison.blastRadiusComparison.delta ?? 'unknown'}.</p><p>Observed severity: {comparison.riskComparison.observedSeverity}. {comparison.riskComparison.explanation}</p></article>; }