import { useEffect, useState } from 'react';
import { getSecurityFindingDependents, getSecuritySummary, listSecurityFindings } from '../services/api';
import type { SecurityDependencyEdge, SecurityFinding, SecuritySummary } from '../types/security';

const emptySummary: SecuritySummary = { total: 0, critical: 0, high: 0, medium: 0, low: 0, info: 0, open: 0, affectedResources: 0, categories: {}, highestSeverity: 'unknown', riskContribution: 0 };
export function SecurityIntelligencePage() {
  const [summary, setSummary] = useState(emptySummary); const [findings, setFindings] = useState<SecurityFinding[]>([]); const [selected, setSelected] = useState<SecurityFinding | null>(null); const [dependents, setDependents] = useState<SecurityDependencyEdge[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([getSecuritySummary(), listSecurityFindings({ limit: 25 })]).then(([nextSummary, nextFindings]) => { setSummary(nextSummary); setFindings(nextFindings.data); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Unable to load security intelligence.')); }, []);
  async function selectFinding(finding: SecurityFinding) { setSelected(finding); setDependents(finding.resourceId ? await getSecurityFindingDependents(finding.resourceId) : []); }
  const direct = selected?.resourceId ? dependents.filter((edge) => edge.targetResourceId === selected.resourceId).map((edge) => edge.sourceResourceId) : []; const transitive = [...new Set(dependents.map((edge) => edge.sourceResourceId).filter((id) => !direct.includes(id)))];
  return <section className="history-section" id="security" aria-labelledby="security-title"><div className="history-heading"><p className="eyebrow">Phase 8 · Evidence-first security</p><h2 id="security-title">Security Intelligence</h2><p className="section-copy">Security findings are evidence-backed observations. Potential dependency blast radius does not imply that dependent resources are themselves vulnerable.</p></div>{error ? <p className="inline-error" role="alert">{error}</p> : <><div className="analysis-summary security-summary"><div><small>Total findings</small><strong>{summary.total}</strong></div><div><small>Critical</small><strong>{summary.critical}</strong></div><div><small>High</small><strong>{summary.high}</strong></div><div><small>Risk contribution</small><strong>{summary.riskContribution}</strong></div></div><div className="record-layout"><div className="record-list">{findings.length === 0 ? <p className="empty-state">No security findings recorded.</p> : findings.map((finding) => <button className={`record-row ${selected?.id === finding.id ? 'record-row--selected' : ''}`} key={finding.id} type="button" onClick={() => void selectFinding(finding)}><span><strong>{finding.title}</strong><small>{finding.severity} · {finding.category} · {finding.source}</small></span><small>{finding.status} · {finding.confidence}%</small></button>)}</div>{selected ? <article className="record-detail"><div className="detail-heading"><div><p className="resource-type">SECURITY FINDING</p><h3>{selected.title}</h3></div><span className="resource-status resource-status--unknown">{selected.severity}</span></div><p className="section-copy">{selected.description}</p><dl className="detail-meta"><div><dt>Confidence</dt><dd>{selected.confidence}%</dd></div><div><dt>Source</dt><dd>{selected.source}</dd></div><div><dt>Evidence</dt><dd>{selected.evidenceIds.join(', ') || 'None recorded'}</dd></div><div><dt>Location</dt><dd>{selected.resourceId ?? 'Not attached'}</dd></div></dl><h4>Potential Blast Radius</h4><p className="section-copy">Potentially affected by dependency relationship. The vulnerability belongs to the resource supported by the finding evidence.</p><dl className="detail-meta"><div><dt>Affected resource</dt><dd>{selected.resourceId ?? 'Unknown'}</dd></div><div><dt>Direct dependents</dt><dd>{direct.length ? direct.join(', ') : 'None'}</dd></div><div><dt>Transitive dependents</dt><dd>{transitive.length ? transitive.join(', ') : 'None'}</dd></div><div><dt>Dependency depth</dt><dd>Up to 10</dd></div><div><dt>Total potentially affected</dt><dd>{1 + direct.length + transitive.length}</dd></div></dl></article> : <div className="detail-placeholder">Select a finding to inspect evidence and potential blast radius.</div>}</div></>}</section>;
}