import { accuracyLevel } from './metricComparisonEngine.js';
import type { PredictionSnapshotDTO, ObservedImpactDTO, PredictionComparisonDTO, ObservedSeverity } from '../types/predictionReality.js';
import { compareSecurityImpact } from './securityComparisonEngine.js';

export function comparePredictionReality(prediction: PredictionSnapshotDTO, observation: ObservedImpactDTO): Omit<PredictionComparisonDTO, 'id' | 'createdAt' | 'updatedAt'> {
  const predictedCategories = [...new Set(prediction.predictedImpact.categories)]; const observedCategories = [...new Set(observation.observedImpact.categories)];
  const confirmedCategories = predictedCategories.filter((category) => observedCategories.includes(category)); const unconfirmedCategories = predictedCategories.filter((category) => !observedCategories.includes(category)); const unexpectedCategories = observedCategories.filter((category) => !predictedCategories.includes(category));
  const predictedResourceIds = [...new Set(prediction.predictedResourceIds)]; const observedResourceIds = [...new Set(observation.observedResources)]; const confirmedResourceIds = predictedResourceIds.filter((id) => observedResourceIds.includes(id)); const unexpectedResourceIds = observedResourceIds.filter((id) => !predictedResourceIds.includes(id));
  const metricComparison = observation.observedMetrics.map((metric) => ({ name: metric.name, predictedDirection: undefined, observedDirection: metric.direction, match: null, baseline: metric.baseline, observed: metric.observed, delta: metric.delta, unit: metric.unit }));
  const observedTotal = observedResourceIds.length > 0 ? observedResourceIds.length : null; const delta = observedTotal === null ? null : observedTotal - prediction.predictedBlastRadius.totalCount;
  const observedSeverity: ObservedSeverity = observation.observedFailures.length > 0 ? observation.observedFailures.reduce<ObservedSeverity>((highest, failure) => severityRank(failure.severity) > severityRank(highest) ? failure.severity : highest, 'none') : observation.status === 'observed' ? 'none' : 'unknown';
  const dimensions: number[] = []; if (predictedCategories.length > 0 && observedCategories.length > 0) dimensions.push((confirmedCategories.length / predictedCategories.length) * 100); if (predictedResourceIds.length > 0 && observedResourceIds.length > 0) dimensions.push((confirmedResourceIds.length / predictedResourceIds.length) * 100); if (metricComparison.some((metric) => metric.predictedDirection !== undefined)) dimensions.push(metricComparison.filter((metric) => metric.predictedDirection !== undefined).every((metric) => metric.match === true) ? 100 : 0); if (observedTotal !== null) dimensions.push(prediction.predictedBlastRadius.totalCount === observedTotal ? 100 : Math.max(0, 100 - Math.abs(delta! / Math.max(1, prediction.predictedBlastRadius.totalCount) * 100)));
  const score = dimensions.length === 0 ? null : Math.round(dimensions.reduce((sum, value) => sum + value, 0) / dimensions.length);
  const securityComparison = compareSecurityImpact(prediction.predictedSecurityFindings, observation.observedSecurityFindings, observation.evidenceIds.length > 0);
  return { changeId: prediction.changeId, predictionId: prediction.id, observationId: observation.id, comparedAt: new Date().toISOString(), impactComparison: { predictedCategories, observedCategories, confirmedCategories, unconfirmedCategories, unexpectedCategories }, resourceComparison: { predictedResourceIds, observedResourceIds, confirmedResourceIds, unexpectedResourceIds }, securityComparison, metricComparison, blastRadiusComparison: { predictedTotal: prediction.predictedBlastRadius.totalCount, observedTotal, delta }, riskComparison: { predictedScore: prediction.predictedRisk.score, observedSeverity, explanation: observedSeverity === 'unknown' ? 'Insufficient evidence to determine observed severity.' : `Observed severity is ${observedSeverity} based only on structured evidence.` }, accuracy: { score, level: accuracyLevel(score) }, summary: observedCategories.length === 0 ? 'No observed impact categories were supported by available evidence.' : `Confirmed ${confirmedCategories.length} predicted impact categor${confirmedCategories.length === 1 ? 'y' : 'ies'}; ${unconfirmedCategories.length} predicted categor${unconfirmedCategories.length === 1 ? 'y was' : 'ies were'} not confirmed by available evidence.`, evidenceIds: observation.evidenceIds };
}
function severityRank(severity: ObservedSeverity): number { return { unknown: -1, none: 0, low: 1, medium: 2, high: 3, critical: 4 }[severity]; }