import mongoose, { Types } from 'mongoose';
import { ChangeModel } from '../models/Change.js';
import { ResourceModel } from '../models/Resource.js';
import { EvidenceModel } from '../models/Evidence.js';
import { SecurityFindingModel } from '../models/SecurityFinding.js';
import { RemediationModel, toRemediationDTO, type RemediationHydratedDocument } from '../models/Remediation.js';
import { AppError } from '../utils/app-error.js';
import type { CreateRemediationInput, RemediationDTO, RemediationFilters, RemediationStatus, ValidationResult } from './remediation.types.js';
import type { PaginatedResult } from '../types/pagination.js';
import { calculateRemediationRisk, rollbackFor, validateActions } from './remediation.engine.js';
import { assertTransition } from './remediation.transitions.js';
import { validateRemediationActions } from './remediation.validation.js';
import { DryRunRemediationExecutor } from './remediation.executor.js';
import { sanitizeObject } from '../utils/sensitive-data.js';

function oid(value: string, field: string): Types.ObjectId { if (!mongoose.isValidObjectId(value)) throw new AppError(400, `${field} must be a valid MongoDB ObjectId.`); return new Types.ObjectId(value); }
async function ref(value: string, field: string, model: typeof ChangeModel | typeof ResourceModel): Promise<Types.ObjectId> { const id = oid(value, field); if (!(await model.exists({ _id: id }))) throw new AppError(404, `${field} reference was not found.`); return id; }
async function refs(values: string[], field: string, model: typeof EvidenceModel | typeof SecurityFindingModel): Promise<Types.ObjectId[]> { const ids = [...new Set(values)].map((value) => oid(value, field)); if (ids.length !== await model.countDocuments({ _id: { $in: ids } })) throw new AppError(404, `One or more ${field} references were not found.`); return ids; }
async function resourceRefs(values: string[], field: string): Promise<Types.ObjectId[]> { const ids = [...new Set(values)].map((value) => oid(value, field)); if (ids.length !== await ResourceModel.countDocuments({ _id: { $in: ids } })) throw new AppError(404, `One or more ${field} references were not found.`); return ids; }
function audit(event: string, status: RemediationStatus, actor: string, details?: Record<string, unknown>) { return { event, status, actor, at: new Date().toISOString(), ...(details ? { details: sanitizeObject(details) } : {}) }; }
function document(value: RemediationHydratedDocument): RemediationDTO { return toRemediationDTO(value); }

export async function createRemediation(input: CreateRemediationInput): Promise<RemediationDTO> {
  const changeId = await ref(input.changeId, 'changeId', ChangeModel); const resourceId = await ref(input.resourceId, 'resourceId', ResourceModel); const evidenceIds = await refs(input.evidenceIds, 'evidenceIds', EvidenceModel); if (evidenceIds.length === 0) throw new AppError(400, 'At least one evidence reference is required.'); const affectedResourceIds = await resourceRefs(input.affectedResourceIds ?? [], 'affectedResourceIds'); const blastRadius = input.blastRadius ?? { directCount: 0, transitiveCount: 0, totalCount: 1 + affectedResourceIds.length, maxDependencyDepth: input.riskContext?.dependencyDepth ?? 0 };
  const securityFindingIds = await refs(input.securityFindingIds ?? [], 'securityFindingIds', SecurityFindingModel); validateActions(input.proposedChanges);
  const risk = calculateRemediationRisk(input.riskContext, input.proposedChanges); const rollback = rollbackFor(input.proposedChanges, input.riskContext); const created = await RemediationModel.create({ ...input, changeId, resourceId, affectedResourceIds, blastRadius, ...(input.investigationId ? { investigationId: oid(input.investigationId, 'investigationId') } : {}), ...(input.predictionId ? { predictionId: oid(input.predictionId, 'predictionId') } : {}), securityFindingIds, evidenceIds, proposedChanges: input.proposedChanges, risk, rollback, status: 'proposed', prStatus: 'not_created', audit: [audit('remediation_created', 'proposed', input.createdBy)], metadata: sanitizeObject(input.metadata ?? {}) }); return document(created);
}
export async function listRemediations(filters: RemediationFilters, page: number, limit: number): Promise<PaginatedResult<RemediationDTO>> { const query: Record<string, unknown> = {}; if (filters.status) query.status = filters.status; if (filters.type) query.type = filters.type; if (filters.changeId) query.changeId = oid(filters.changeId, 'changeId'); if (filters.resourceId) query.resourceId = oid(filters.resourceId, 'resourceId'); const [items, total] = await Promise.all([RemediationModel.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), RemediationModel.countDocuments(query)]); return { data: items.map((item) => document(item as RemediationHydratedDocument)), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }; }
export async function getRemediation(id: string): Promise<RemediationDTO> { const item = await RemediationModel.findById(oid(id, 'remediationId')); if (!item) throw new AppError(404, 'Remediation not found.'); return document(item as RemediationHydratedDocument); }
export async function updateRemediation(id: string, input: Partial<Pick<CreateRemediationInput, 'title' | 'description' | 'reason' | 'metadata'>>): Promise<RemediationDTO> { const item = await RemediationModel.findById(oid(id, 'remediationId')); if (!item) throw new AppError(404, 'Remediation not found.'); if (!['proposed', 'analyzed', 'generated'].includes(item.status)) throw new AppError(409, 'Only an unvalidated remediation may be edited.'); if (input.title !== undefined) item.title = input.title; if (input.description !== undefined) item.description = input.description; if (input.reason !== undefined) item.reason = input.reason; if (input.metadata !== undefined) item.metadata = sanitizeObject(input.metadata); await item.save(); return document(item as RemediationHydratedDocument); }
async function load(id: string) { const item = await RemediationModel.findById(oid(id, 'remediationId')); if (!item) throw new AppError(404, 'Remediation not found.'); return item; }
async function move(item: RemediationHydratedDocument, to: RemediationStatus, actor: string, details?: Record<string, unknown>) { assertTransition(item.status, to); item.status = to; item.audit.push(audit(`remediation_${to}`, to, actor, details)); await item.save(); }
export async function analyzeRemediation(id: string, actor = 'system'): Promise<RemediationDTO> { const item = await load(id); await move(item as RemediationHydratedDocument, 'analyzed', actor); return document(item as RemediationHydratedDocument); }
export async function generateRemediation(id: string, actor = 'system'): Promise<RemediationDTO> { const item = await load(id); await move(item as RemediationHydratedDocument, 'generated', actor); return document(item as RemediationHydratedDocument); }
export async function validateRemediation(id: string, actor = 'system'): Promise<RemediationDTO> { const item = await load(id) as RemediationHydratedDocument; const validation: ValidationResult = validateRemediationActions(item.proposedChanges); item.validation = validation; await move(item, validation.valid ? 'validated' : 'validation_failed', actor, { schemaValidated: validation.schemaValidated }); return document(item); }
export async function preparePR(id: string, actor = 'system'): Promise<RemediationDTO> { const item = await load(id) as RemediationHydratedDocument; if (!item.validation?.valid) throw new AppError(409, 'Remediation must pass schema validation before PR preparation.'); await move(item, 'pr_created', actor); item.prStatus = 'prepared'; item.prProposal = { title: item.title, description: item.description, proposedChanges: item.proposedChanges, evidenceIds: item.evidenceIds.map((value) => value.toString()), risk: item.risk, rollback: item.rollback, note: 'Prepared proposal only; no GitHub API was called.' }; await item.save(); await move(item, 'awaiting_approval', actor); return document(item); }
export async function approveRemediation(id: string, approvedBy: string, reason: string): Promise<RemediationDTO> { const item = await load(id) as RemediationHydratedDocument; item.approval = { approved: true, approvedBy, approvedAt: new Date().toISOString(), reason, metadata: {} }; await move(item, 'approved', approvedBy); return document(item); }
export async function rejectRemediation(id: string, rejectedBy: string, reason: string): Promise<RemediationDTO> { const item = await load(id) as RemediationHydratedDocument; item.approval = { approved: false, approvedBy: rejectedBy, approvedAt: new Date().toISOString(), reason, metadata: {} }; await move(item, 'rejected', rejectedBy); return document(item); }
export async function dryRunRemediation(id: string, actor = 'system'): Promise<RemediationDTO> { const item = await load(id) as RemediationHydratedDocument; if (!item.approval?.approved) throw new AppError(403, 'Explicit human approval is required before dry run.'); await move(item, 'executing', actor); const result = await new DryRunRemediationExecutor().execute(item.proposedChanges); item.execution = result; await item.save(); await move(item, 'executed', actor, { mode: result.mode, success: result.success }); return document(item); }
export async function verifyRemediation(id: string, actor = 'system', verificationEvidenceIds: string[] = []): Promise<RemediationDTO> { const item = await load(id) as RemediationHydratedDocument; const verifiedEvidenceIds = verificationEvidenceIds.length > 0 ? await refs(verificationEvidenceIds, 'verificationEvidenceIds', EvidenceModel) : []; const result = await new DryRunRemediationExecutor().verify(item.proposedChanges, verifiedEvidenceIds.map((value) => value.toString())); item.verification = result; await move(item, result.status === 'passed' ? 'verified' : 'verification_failed', actor, { verificationStatus: result.status }); return document(item); }