import type { RequestHandler } from 'express';
import { analyzeRemediation, approveRemediation, createRemediation, dryRunRemediation, generateRemediation, getRemediation, listRemediations, preparePR, rejectRemediation, updateRemediation, validateRemediation, verifyRemediation } from './remediation.service.js';
import { remediationStatuses, remediationTypes, type CreateRemediationInput, type RemediationFilters, type RemediationAction } from './remediation.types.js';
import { AppError } from '../utils/app-error.js';
import { parseObject, parsePagination, parseQueryString, pathString, requiredString } from '../utils/request-validation.js';
import { validateActions } from './remediation.engine.js';
function object(value: unknown, field: string): Record<string, unknown> { const result = parseObject(value, field, true); if (!result) throw new AppError(400, `${field} must be an object.`); return result; }
function enumValue<T extends string>(value: unknown, field: string, values: readonly T[]): T { const result = requiredString(value, field, 40); if (!values.includes(result as T)) throw new AppError(400, `${field} must be one of: ${values.join(', ')}.`); return result as T; }
function actions(value: unknown): RemediationAction[] { if (!Array.isArray(value)) throw new AppError(400, 'proposedChanges must be an array.'); return value.map((item) => object(item, 'proposedChanges') as unknown as RemediationAction); }
function createInput(body: unknown): CreateRemediationInput { const value = object(body, 'body'); const evidenceIds = value.evidenceIds; if (!Array.isArray(evidenceIds) || evidenceIds.some((item) => typeof item !== 'string')) throw new AppError(400, 'evidenceIds must be an array of strings.'); const affectedResourceIds = value.affectedResourceIds; if (affectedResourceIds !== undefined && (!Array.isArray(affectedResourceIds) || affectedResourceIds.some((item) => typeof item !== 'string'))) throw new AppError(400, 'affectedResourceIds must be an array of strings.'); const proposedChanges = actions(value.proposedChanges); validateActions(proposedChanges); const riskContext = value.riskContext === undefined ? undefined : object(value.riskContext, 'riskContext'); return { changeId: requiredString(value.changeId, 'changeId', 24), resourceId: requiredString(value.resourceId, 'resourceId', 24), ...(affectedResourceIds ? { affectedResourceIds } : {}), ...(value.blastRadius !== undefined ? { blastRadius: object(value.blastRadius, 'blastRadius') as unknown as CreateRemediationInput['blastRadius'] } : {}), ...(value.investigationId !== undefined ? { investigationId: requiredString(value.investigationId, 'investigationId', 24) } : {}), ...(value.securityFindingIds !== undefined ? { securityFindingIds: Array.isArray(value.securityFindingIds) ? value.securityFindingIds.map((id) => requiredString(id, 'securityFindingIds', 24)) : [] } : {}), ...(value.predictionId !== undefined ? { predictionId: requiredString(value.predictionId, 'predictionId', 24) } : {}), type: enumValue(value.type, 'type', remediationTypes), title: requiredString(value.title, 'title', 240), description: requiredString(value.description, 'description', 2000), reason: requiredString(value.reason, 'reason', 2000), proposedChanges, evidenceIds, createdBy: requiredString(value.createdBy, 'createdBy', 160), ...(value.metadata !== undefined ? { metadata: object(value.metadata, 'metadata') } : {}), ...(riskContext ? { riskContext: riskContext as CreateRemediationInput['riskContext'] } : {}) }; }
function filters(query: Record<string, unknown>): RemediationFilters { return { ...(query.status !== undefined ? { status: enumValue(parseQueryString(query.status, 'status'), 'status', remediationStatuses) } : {}), ...(query.type !== undefined ? { type: enumValue(parseQueryString(query.type, 'type'), 'type', remediationTypes) } : {}), changeId: parseQueryString(query.changeId, 'changeId'), resourceId: parseQueryString(query.resourceId, 'resourceId') }; }
function actor(request: { body?: unknown }): string { const value = request.body && typeof request.body === 'object' ? request.body as Record<string, unknown> : {}; return requiredString(value.actor ?? value.approvedBy ?? value.rejectedBy ?? 'system', 'actor', 160); }
function reason(request: { body?: unknown }): string { const value = request.body && typeof request.body === 'object' ? request.body as Record<string, unknown> : {}; return requiredString(value.reason, 'reason', 1000); }
export const postRemediation: RequestHandler = async (request, response) => response.status(201).json({ success: true, data: await createRemediation(createInput(request.body)) });
export const listRemediation: RequestHandler = async (request, response) => { const { page, limit } = parsePagination(request.query as Record<string, unknown>); const result = await listRemediations(filters(request.query as Record<string, unknown>), page, limit); response.status(200).json({ success: true, data: result.data, pagination: result.pagination }); };
export const getRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await getRemediation(pathString(request.params.id, 'id')) });
export const patchRemediation: RequestHandler = async (request, response) => { const value = object(request.body, 'body'); const allowed = ['title', 'description', 'reason', 'metadata']; if (Object.keys(value).some((key) => !allowed.includes(key))) throw new AppError(400, 'Only title, description, reason, and metadata may be updated.'); response.status(200).json({ success: true, data: await updateRemediation(pathString(request.params.id, 'id'), value as Pick<CreateRemediationInput, 'title' | 'description' | 'reason' | 'metadata'>) }); };
export const analyzeRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await analyzeRemediation(pathString(request.params.id, 'id'), actor(request)) });
export const generateRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await generateRemediation(pathString(request.params.id, 'id'), actor(request)) });
export const validateRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await validateRemediation(pathString(request.params.id, 'id'), actor(request)) });
export const preparePRController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await preparePR(pathString(request.params.id, 'id'), actor(request)) });
export const approveRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await approveRemediation(pathString(request.params.id, 'id'), actor(request), reason(request)) });
export const rejectRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await rejectRemediation(pathString(request.params.id, 'id'), actor(request), reason(request)) });
export const dryRunRemediationController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await dryRunRemediation(pathString(request.params.id, 'id'), actor(request)) });
export const verifyRemediationController: RequestHandler = async (request, response) => { const value = request.body && typeof request.body === 'object' ? request.body as Record<string, unknown> : {}; const evidenceIds = value.evidenceIds === undefined ? [] : value.evidenceIds; if (!Array.isArray(evidenceIds) || evidenceIds.some((id) => typeof id !== 'string')) throw new AppError(400, 'Verification evidenceIds must be an array of strings.'); response.status(200).json({ success: true, data: await verifyRemediation(pathString(request.params.id, 'id'), actor(request), evidenceIds) }); };