import mongoose, { Types } from 'mongoose';
import { ChangeModel, type ChangeHydratedDocument } from '../models/Change.js';
import { ChangeAnalysisModel, toChangeAnalysisDTO } from '../models/ChangeAnalysis.js';
import { PredictionComparisonModel, toPredictionComparisonDTO } from '../models/PredictionComparison.js';
import { ObservedImpactModel, toObservedImpactDTO } from '../models/ObservedImpact.js';
import { SecurityFindingModel } from '../models/SecurityFinding.js';
import { RemediationModel } from '../models/Remediation.js';
import { ResourceModel } from '../models/Resource.js';
import { AdvancedInsightModel, toAdvancedInsightDTO, type AdvancedInsightHydratedDocument } from '../models/AdvancedInsight.js';
import type { PaginatedResult } from '../types/pagination.js';
import type { AdvancedInsightDTO, HistoricalFeature, HistoricalPattern, PredictionAccuracy, PredictionBias, RiskTrend, SimilarChange } from './intelligence.types.js';
import { calculatePredictionAccuracy, calculateRiskTrend, classifyOutcome, compareHistoricalFeatures, detectPredictionBias } from './intelligence.engine.js';
import { AppError } from '../utils/app-error.js';

const MAX_HISTORY = 100; const MAX_SIMILAR = 20;
function id(value: string, field: string): Types.ObjectId { if (!mongoose.isValidObjectId(value)) throw new AppError(400, `${field} must be a valid MongoDB ObjectId.`); return new Types.ObjectId(value); }
async function feature(change: ChangeHydratedDocument | null): Promise<HistoricalFeature | null> {
  if (!change) return null;
  const [analysis, observation, comparison, resource, findings, remediation] = await Promise.all([
    ChangeAnalysisModel.findOne({ changeId: change._id }), ObservedImpactModel.findOne({ changeId: change._id }).sort({ createdAt: -1 }), PredictionComparisonModel.findOne({ changeId: change._id }).sort({ comparedAt: -1 }), ResourceModel.findById(change.resourceId).select({ type: 1, environment: 1 }), SecurityFindingModel.find({ changeId: change._id }).limit(100).select({ category: 1, evidenceIds: 1 }), RemediationModel.findOne({ changeId: change._id }).sort({ createdAt: -1 }).select({ status: 1, verification: 1 })
  ]);
  const analysisDTO = analysis ? toChangeAnalysisDTO(analysis) : undefined; const observationDTO = observation ? toObservedImpactDTO(observation) : undefined; const comparisonDTO = comparison ? toPredictionComparisonDTO(comparison) : undefined;
  const evidenceIds = [...new Set([...change.evidenceIds.map((value) => value.toString()), ...(analysisDTO?.evidenceIds ?? []), ...(observationDTO?.evidenceIds ?? []), ...(comparisonDTO?.evidenceIds ?? [])])].slice(0, 100);
  return { changeId: change._id.toString(), resourceId: change.resourceId.toString(), resourceType: resource?.type, environment: resource?.environment, changeType: change.changeType, riskScore: analysisDTO?.risk.score, riskLevel: analysisDTO?.risk.level, changedItemCount: analysisDTO?.changedItems.length ?? 0, impactCategories: analysisDTO?.impact.categories ?? [], paths: analysisDTO?.changedItems.map((item) => item.path) ?? [], affectedResourceIds: [...new Set([...(analysisDTO?.directlyAffectedResourceIds ?? []), ...(analysisDTO?.transitivelyAffectedResourceIds ?? [])])], dependencyResourceIds: analysisDTO?.transitivelyAffectedResourceIds ?? [], securityCategories: [...new Set(findings.map((finding) => finding.category))], outcome: classifyOutcome({ changeStatus: change.status, observationStatus: observationDTO?.status, observedSeverity: comparisonDTO?.riskComparison.observedSeverity, verificationStatus: remediation?.verification?.status, comparisonAccuracy: comparisonDTO?.accuracy.score, evidenceCount: evidenceIds.length }), evidenceIds, timestamp: change.timestamp.toISOString() };
}
async function featuresFor(query: Record<string, unknown>, limit = MAX_HISTORY): Promise<HistoricalFeature[]> { const changes = await ChangeModel.find(query).sort({ timestamp: -1 }).limit(Math.min(limit, MAX_HISTORY)); const values = await Promise.all(changes.map((change) => feature(change))); return values.filter((value): value is HistoricalFeature => value !== null); }
export async function findSimilarChanges(changeId: string, limit = 5): Promise<SimilarChange[]> { const currentChange = await ChangeModel.findById(id(changeId, 'changeId')); const current = await feature(currentChange); if (!current || !currentChange) throw new AppError(404, 'Change not found.'); const history = (await featuresFor({ resourceId: current.resourceId, _id: { $ne: currentChange._id } }, MAX_SIMILAR)).filter((item) => item.evidenceIds.length > 0); return history.map((item) => compareHistoricalFeatures(current, item)).sort((left, right) => right.similarityScore - left.similarityScore).slice(0, Math.min(limit, MAX_SIMILAR)); }
export async function getHistoricalOutcomes(resourceId: string, limit = 25): Promise<HistoricalFeature[]> { return featuresFor({ resourceId: id(resourceId, 'resourceId') }, limit); }
export async function getHistoricalRisk(resourceId: string, windowDays?: number): Promise<RiskTrend> { const query: Record<string, unknown> = { resourceId: id(resourceId, 'resourceId') }; if (windowDays) query.timestamp = { $gte: new Date(Date.now() - windowDays * 86400000) }; return calculateRiskTrend(await featuresFor(query), windowDays ?? null); }
export async function getPredictionAccuracyHistory(resourceId: string): Promise<PredictionAccuracy> { const changes = await ChangeModel.find({ resourceId: id(resourceId, 'resourceId') }).limit(MAX_HISTORY); const comparisons = await Promise.all(changes.map((change) => PredictionComparisonModel.findOne({ changeId: change._id }).sort({ comparedAt: -1 }))); return calculatePredictionAccuracy(comparisons.filter(Boolean).map((comparison) => { const value = toPredictionComparisonDTO(comparison!); return { accuracy: value.accuracy.score, level: value.accuracy.level, evidenceIds: value.evidenceIds }; })); }
export async function getSimilarHistory(changeId: string): Promise<{ currentChangeId: string; similar: SimilarChange[]; status: 'available' | 'insufficient_evidence' }> { const similar = await findSimilarChanges(changeId); return { currentChangeId: changeId, similar, status: similar.length ? 'available' : 'insufficient_evidence' }; }
export async function getPatterns(resourceId?: string): Promise<HistoricalPattern[]> { const features = resourceId ? await getHistoricalOutcomes(resourceId, MAX_HISTORY) : await featuresFor({}, MAX_HISTORY); const groups = new Map<string, HistoricalFeature[]>(); features.filter((item) => item.evidenceIds.length > 0).forEach((item) => { const key = `${item.resourceId}:${item.changeType}:${item.paths[0] ?? 'unknown'}`; groups.set(key, [...(groups.get(key) ?? []), item]); }); return [...groups.values()].filter((group) => group.length >= 2).map((group) => { const failures = group.filter((item) => ['failed', 'degraded', 'reverted'].includes(item.outcome)); const confidence = group.length >= 5 ? 'high' : group.length >= 3 ? 'medium' : 'low'; return { type: failures.length ? 'recurring_failure' : 'historical_warning', title: `${failures.length} of ${group.length} similar ${group[0].changeType} changes were associated with degraded outcomes`, description: `Historical evidence indicates an association for resource ${group[0].resourceId}; it does not establish causation or predict a guaranteed failure.`, sampleSize: group.length, matchingChangeIds: group.map((item) => item.changeId), outcomes: group.map((item) => item.outcome), evidenceIds: [...new Set(group.flatMap((item) => item.evidenceIds))].slice(0, 100), confidence, limitations: ['Historical association is not causation.', 'Current state requires current evidence.'] }; }); }
async function materializeInsights(patterns: HistoricalPattern[]): Promise<void> {
  await Promise.all(patterns.slice(0, 20).map((pattern) => AdvancedInsightModel.findOneAndUpdate(
    { type: pattern.type, title: pattern.title },
    { type: pattern.type, title: pattern.title, description: pattern.description, severity: pattern.type === 'recurring_failure' ? 'high' : 'medium', confidence: pattern.confidence === 'high' ? 90 : pattern.confidence === 'medium' ? 70 : 50, resourceIds: [], changeIds: pattern.matchingChangeIds.map((value) => id(value, 'changeId')), evidenceIds: pattern.evidenceIds.map((value) => id(value, 'evidenceId')), supportingPatterns: [pattern], recommendation: 'Review the supporting historical changes and current evidence before making another similar change.', status: 'active', metadata: {} },
    { upsert: true, new: true, runValidators: true }
  )));
}
export async function listInsights(page: number, limit: number, status?: string): Promise<PaginatedResult<AdvancedInsightDTO>> { const query = status ? { status } : {}; const [items, total] = await Promise.all([AdvancedInsightModel.find(query).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit), AdvancedInsightModel.countDocuments(query)]); return { data: items.map((item) => toAdvancedInsightDTO(item as AdvancedInsightHydratedDocument)), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }; }
export async function getInsight(idValue: string): Promise<AdvancedInsightDTO> { const item = await AdvancedInsightModel.findById(id(idValue, 'insightId')); if (!item) throw new AppError(404, 'Insight not found.'); return toAdvancedInsightDTO(item as AdvancedInsightHydratedDocument); }
export async function updateInsightStatus(idValue: string, status: 'acknowledged' | 'dismissed'): Promise<AdvancedInsightDTO> { const item = await AdvancedInsightModel.findByIdAndUpdate(id(idValue, 'insightId'), { status }, { new: true, runValidators: true }); if (!item) throw new AppError(404, 'Insight not found.'); return toAdvancedInsightDTO(item as AdvancedInsightHydratedDocument); }
export async function overview(): Promise<{ riskTrend: RiskTrend; predictionAccuracy: PredictionAccuracy; patterns: HistoricalPattern[]; status: 'available' | 'insufficient_evidence' }> { const features = await featuresFor({}, MAX_HISTORY); const riskTrend = calculateRiskTrend(features, null); const comparisons = await PredictionComparisonModel.find().sort({ comparedAt: -1 }).limit(MAX_HISTORY); const predictionAccuracy = calculatePredictionAccuracy(comparisons.map((comparison) => { const value = toPredictionComparisonDTO(comparison); return { accuracy: value.accuracy.score, level: value.accuracy.level, evidenceIds: value.evidenceIds }; })); const patterns = await getPatterns(); await materializeInsights(patterns); return { riskTrend, predictionAccuracy, patterns: patterns.slice(0, 20), status: features.length ? 'available' : 'insufficient_evidence' }; }
export async function remediationPerformance(): Promise<{ status: 'available' | 'insufficient_evidence'; sampleSize: number; verified: number; failed: number; successRate: number | null; evidenceIds: string[] }> { const remediations = await RemediationModel.find({ status: { $in: ['verified', 'verification_failed'] } }).limit(MAX_HISTORY).select({ status: 1, evidenceIds: 1 }); if (!remediations.length) return { status: 'insufficient_evidence', sampleSize: 0, verified: 0, failed: 0, successRate: null, evidenceIds: [] }; const verified = remediations.filter((item) => item.status === 'verified').length; return { status: 'available', sampleSize: remediations.length, verified, failed: remediations.length - verified, successRate: verified / remediations.length, evidenceIds: [...new Set(remediations.flatMap((item) => item.evidenceIds.map((value) => value.toString())))].slice(0, 100) }; }
export async function predictionBias(resourceId: string): Promise<PredictionBias> { const changes = await ChangeModel.find({ resourceId: id(resourceId, 'resourceId') }).limit(MAX_HISTORY); const values = await Promise.all(changes.map(async (change) => { const comparison = await PredictionComparisonModel.findOne({ changeId: change._id }).sort({ comparedAt: -1 }); if (!comparison) return null; const value = toPredictionComparisonDTO(comparison); return { predictedScore: value.riskComparison.predictedScore, observedSeverity: value.riskComparison.observedSeverity, evidenceIds: value.evidenceIds }; })); return detectPredictionBias(values.filter((value): value is NonNullable<typeof value> => value !== null)); }
export async function getChangeHistory(changeId: string): Promise<HistoricalFeature[]> { const change = await ChangeModel.findById(id(changeId, 'changeId')); if (!change) throw new AppError(404, 'Change not found.'); return getHistoricalOutcomes(change.resourceId.toString(), MAX_HISTORY); }
export async function getSecurityPatterns(): Promise<HistoricalPattern[]> { const features = await featuresFor({}, MAX_HISTORY); const recurring = features.filter((item) => item.securityCategories.length > 0 && item.evidenceIds.length > 0); if (recurring.length < 2) return []; return [{ type: 'repeated_security_issue', title: `Security findings recurred across ${recurring.length} historical changes`, description: 'Historical security evidence indicates recurrence; it does not create a current SecurityFinding.', sampleSize: recurring.length, matchingChangeIds: recurring.map((item) => item.changeId), outcomes: recurring.map((item) => item.outcome), evidenceIds: [...new Set(recurring.flatMap((item) => item.evidenceIds))].slice(0, 100), confidence: recurring.length >= 5 ? 'high' : 'medium', limitations: ['History does not establish that the issue is currently present.'] }]; }
export async function getDependencyPatterns(): Promise<HistoricalPattern[]> { const features = await featuresFor({}, MAX_HISTORY); const related = features.filter((item) => item.dependencyResourceIds.length > 0 && item.evidenceIds.length > 0 && ['failed', 'degraded', 'reverted'].includes(item.outcome)); if (related.length < 2) return []; return [{ type: 'dependency_risk', title: `Historical changes across dependency paths were associated with ${related.length} degraded outcomes`, description: 'Historical changes affecting these dependency paths were associated with outcomes; graph structure alone does not establish causation.', sampleSize: related.length, matchingChangeIds: related.map((item) => item.changeId), outcomes: related.map((item) => item.outcome), evidenceIds: [...new Set(related.flatMap((item) => item.evidenceIds))].slice(0, 100), confidence: related.length >= 5 ? 'high' : 'medium', limitations: ['Dependency relationships do not prove causal impact.'] }]; }
