import type { RequestHandler } from 'express';
import { analyzeChangeSecurity, createSecurityFinding, deleteSecurityFinding, getSecurityFinding, getSecurityFindingsForChange, getSecurityFindingsForResource, getSecuritySummary, listSecurityFindings, updateSecurityFinding } from '../services/securityAnalysisService.js';
import { securityCategories, securitySeverities, securitySources, securityStatuses, type CreateSecurityFindingInput, type SecurityFindingFilters } from '../types/security.js';
import { AppError } from '../utils/app-error.js';
import { parseDate, parseObject, parsePagination, parseQueryString, pathString, requiredString } from '../utils/request-validation.js';
function record(value: unknown): Record<string, unknown> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new AppError(400, 'Request body must be a JSON object.'); return value as Record<string, unknown>; }
function enumValue<T extends string>(value: unknown, field: string, values: readonly T[]): T { const result = requiredString(value, field, 40); if (!values.includes(result as T)) throw new AppError(400, `${field} must be one of: ${values.join(', ')}.`); return result as T; }
function input(body: unknown): CreateSecurityFindingInput { const value = record(body); const allowed = ['resourceId', 'changeId', 'evidenceIds', 'source', 'category', 'severity', 'title', 'description', 'ruleId', 'cve', 'cwe', 'package', 'installedVersion', 'fixedVersion', 'location', 'status', 'confidence', 'remediation', 'metadata', 'detectedAt']; const unsupported = Object.keys(value).find((key) => !allowed.includes(key)); if (unsupported) throw new AppError(400, `Unsupported security finding field: ${unsupported}.`); const evidenceIds = value.evidenceIds === undefined ? [] : value.evidenceIds; if (!Array.isArray(evidenceIds) || evidenceIds.some((id) => typeof id !== 'string')) throw new AppError(400, 'evidenceIds must be an array of strings.'); const confidence = value.confidence === undefined ? undefined : value.confidence; if (confidence !== undefined && typeof confidence !== 'number') throw new AppError(400, 'confidence must be a number.'); return { ...(value.resourceId !== undefined ? { resourceId: requiredString(value.resourceId, 'resourceId', 24) } : {}), ...(value.changeId !== undefined ? { changeId: requiredString(value.changeId, 'changeId', 24) } : {}), evidenceIds, source: enumValue(value.source, 'source', securitySources), category: enumValue(value.category, 'category', securityCategories), ...(value.severity !== undefined ? { severity: enumValue(value.severity, 'severity', securitySeverities) } : {}), title: requiredString(value.title, 'title', 240), description: requiredString(value.description, 'description', 2000), ...(value.ruleId !== undefined ? { ruleId: requiredString(value.ruleId, 'ruleId', 160) } : {}), ...(value.cve !== undefined ? { cve: requiredString(value.cve, 'cve', 80) } : {}), ...(value.cwe !== undefined ? { cwe: requiredString(value.cwe, 'cwe', 80) } : {}), ...(value.package !== undefined ? { package: requiredString(value.package, 'package', 200) } : {}), ...(value.installedVersion !== undefined ? { installedVersion: requiredString(value.installedVersion, 'installedVersion', 80) } : {}), ...(value.fixedVersion !== undefined ? { fixedVersion: requiredString(value.fixedVersion, 'fixedVersion', 80) } : {}), ...(value.location !== undefined ? { location: parseObject(value.location, 'location', true) } : {}), ...(value.status !== undefined ? { status: enumValue(value.status, 'status', securityStatuses) } : {}), ...(confidence !== undefined ? { confidence } : {}), ...(value.remediation !== undefined ? { remediation: parseObject(value.remediation, 'remediation', true) as CreateSecurityFindingInput['remediation'] } : {}), ...(value.metadata !== undefined ? { metadata: parseObject(value.metadata, 'metadata', true) } : {}), detectedAt: parseDate(value.detectedAt, 'detectedAt', true)!.toISOString() }; }
function filters(query: Record<string, unknown>): SecurityFindingFilters { return { ...(query.severity !== undefined ? { severity: enumValue(parseQueryString(query.severity, 'severity'), 'severity', securitySeverities) } : {}), ...(query.category !== undefined ? { category: enumValue(parseQueryString(query.category, 'category'), 'category', securityCategories) } : {}), ...(query.status !== undefined ? { status: enumValue(parseQueryString(query.status, 'status'), 'status', securityStatuses) } : {}), ...(query.source !== undefined ? { source: enumValue(parseQueryString(query.source, 'source'), 'source', securitySources) } : {}), resourceId: parseQueryString(query.resourceId, 'resourceId'), changeId: parseQueryString(query.changeId, 'changeId') }; }
export const postSecurityFinding: RequestHandler = async (request, response) => response.status(201).json({ success: true, data: await createSecurityFinding(input(request.body)) });
export const listSecurity: RequestHandler = async (request, response) => { const { page, limit } = parsePagination(request.query as Record<string, unknown>); const result = await listSecurityFindings(filters(request.query as Record<string, unknown>), page, limit); response.status(200).json({ success: true, data: result.data, pagination: result.pagination }); };
export const getSecurity: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await getSecurityFinding(pathString(request.params.id, 'id')) });
export const patchSecurity: RequestHandler = async (request, response) => { const value = record(request.body); const allowed = ['status', 'remediation', 'metadata']; const unsupported = Object.keys(value).find((key) => !allowed.includes(key)); if (unsupported) throw new AppError(400, `Unsupported security update field: ${unsupported}.`); response.status(200).json({ success: true, data: await updateSecurityFinding(pathString(request.params.id, 'id'), { ...(value.status !== undefined ? { status: enumValue(value.status, 'status', securityStatuses) } : {}), ...(value.remediation !== undefined ? { remediation: parseObject(value.remediation, 'remediation', true) as CreateSecurityFindingInput['remediation'] } : {}), ...(value.metadata !== undefined ? { metadata: parseObject(value.metadata, 'metadata', true) } : {}) }) }); };
export const removeSecurity: RequestHandler = async (request, response) => { await deleteSecurityFinding(pathString(request.params.id, 'id')); response.status(200).json({ success: true, data: null }); };
export const listChangeSecurity: RequestHandler = async (request, response) => { const { page, limit } = parsePagination(request.query as Record<string, unknown>); const result = await getSecurityFindingsForChange(pathString(request.params.changeId, 'changeId'), page, limit); response.status(200).json({ success: true, data: result.data, pagination: result.pagination }); };
export const listResourceSecurity: RequestHandler = async (request, response) => { const { page, limit } = parsePagination(request.query as Record<string, unknown>); const result = await getSecurityFindingsForResource(pathString(request.params.resourceId, 'resourceId'), page, limit); response.status(200).json({ success: true, data: result.data, pagination: result.pagination }); };
export const securitySummary: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await getSecuritySummary(filters(request.query as Record<string, unknown>)) });
export const analyzeChangeSecurityController: RequestHandler = async (request, response) => response.status(200).json({ success: true, data: await analyzeChangeSecurity(pathString(request.params.changeId, 'changeId')) });