import { Schema, Types, model, type HydratedDocument } from 'mongoose';
import { sanitizeObject } from '../utils/sensitive-data.js';
import type { AIAnalysisResult, ReasoningItemType } from '../ai/types.js';

export interface InvestigationDocument { changeId: Types.ObjectId; resourceId: Types.ObjectId; analysisId?: Types.ObjectId; predictionId?: Types.ObjectId; observationId?: Types.ObjectId; comparisonId?: Types.ObjectId; type: 'change_analysis' | 'incident_rca' | 'prediction_explanation'; status: 'pending' | 'completed' | 'failed'; summary?: string; rootCause?: { statement: string; confidence: number; evidenceIds: Types.ObjectId[] }; hypotheses: Array<{ title: string; explanation: string; confidence: number; supportingEvidenceIds: Types.ObjectId[]; contradictingEvidenceIds: Types.ObjectId[] }>; reasoning: Array<{ statement: string; type: ReasoningItemType }>; impactExplanation?: string; predictionRealityExplanation?: string; recommendations: Array<{ title: string; explanation: string; priority: string; safe: boolean; supportingEvidenceIds: Types.ObjectId[] }>; limitations: string[]; provider: string; model: string; promptVersion: string; latencyMs?: number; errorCode?: string; errorMessage?: string; createdAt: Date; updatedAt: Date; }

const reasoningSchema = new Schema({ statement: { type: String, required: true }, type: { type: String, enum: ['fact', 'inference', 'hypothesis'], required: true } }, { _id: false });
const hypothesisSchema = new Schema({ title: String, explanation: String, confidence: Number, supportingEvidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }], contradictingEvidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }] }, { _id: false });
const recommendationSchema = new Schema({ title: String, explanation: String, priority: String, safe: Boolean, supportingEvidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }] }, { _id: false });
const schema = new Schema<InvestigationDocument>({ changeId: { type: Schema.Types.ObjectId, ref: 'Change', required: true }, resourceId: { type: Schema.Types.ObjectId, ref: 'Resource', required: true }, analysisId: { type: Schema.Types.ObjectId, ref: 'ChangeAnalysis' }, predictionId: { type: Schema.Types.ObjectId, ref: 'PredictionSnapshot' }, observationId: { type: Schema.Types.ObjectId, ref: 'ObservedImpact' }, comparisonId: { type: Schema.Types.ObjectId, ref: 'PredictionComparison' }, type: { type: String, enum: ['change_analysis', 'incident_rca', 'prediction_explanation'], required: true }, status: { type: String, enum: ['pending', 'completed', 'failed'], required: true }, summary: String, rootCause: { statement: String, confidence: Number, evidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }] }, hypotheses: [hypothesisSchema], reasoning: [reasoningSchema], impactExplanation: String, predictionRealityExplanation: String, recommendations: [recommendationSchema], limitations: [String], provider: { type: String, required: true }, model: { type: String, required: true }, promptVersion: { type: String, required: true }, latencyMs: Number, errorCode: String, errorMessage: String }, { timestamps: true });
schema.index({ changeId: 1, createdAt: -1 });
export type InvestigationDocumentHydrated = HydratedDocument<InvestigationDocument>;
export const InvestigationModel = model<InvestigationDocument>('Investigation', schema);

function ids(values: string[]): Types.ObjectId[] { return values.map((value) => new Types.ObjectId(value)); }
export function toInvestigationDTO(doc: InvestigationDocumentHydrated) { return { id: doc._id.toString(), changeId: doc.changeId.toString(), resourceId: doc.resourceId.toString(), ...(doc.analysisId ? { analysisId: doc.analysisId.toString() } : {}), ...(doc.predictionId ? { predictionId: doc.predictionId.toString() } : {}), ...(doc.observationId ? { observationId: doc.observationId.toString() } : {}), ...(doc.comparisonId ? { comparisonId: doc.comparisonId.toString() } : {}), type: doc.type, status: doc.status, summary: doc.summary, rootCause: doc.rootCause ? { statement: doc.rootCause.statement, confidence: doc.rootCause.confidence, evidenceIds: doc.rootCause.evidenceIds.map((id) => id.toString()) } : undefined, hypotheses: doc.hypotheses.map((item) => ({ title: item.title, explanation: item.explanation, confidence: item.confidence, supportingEvidenceIds: item.supportingEvidenceIds.map((id) => id.toString()), contradictingEvidenceIds: item.contradictingEvidenceIds.map((id) => id.toString()) })), reasoning: doc.reasoning, impactExplanation: doc.impactExplanation, predictionRealityExplanation: doc.predictionRealityExplanation, recommendations: doc.recommendations.map((item) => ({ title: item.title, explanation: item.explanation, priority: item.priority, safe: item.safe, supportingEvidenceIds: item.supportingEvidenceIds.map((id) => id.toString()) })), limitations: doc.limitations, provider: doc.provider, model: doc.model, promptVersion: doc.promptVersion, latencyMs: doc.latencyMs, errorCode: doc.errorCode, errorMessage: doc.errorMessage, createdAt: doc.createdAt.toISOString(), updatedAt: doc.updatedAt.toISOString() }; }