import { Schema, Types, model, type HydratedDocument } from 'mongoose';
import { sanitizeObject } from '../utils/sensitive-data.js';
import type { ObservedImpactDTO, ObservationStatus, MetricObservation, ObservedSeverity } from '../types/predictionReality.js';

export interface ObservedImpactDocument { changeId: Types.ObjectId; predictionId: Types.ObjectId; resourceId: Types.ObjectId; observationWindow: { start: Date; end: Date }; evidenceIds: Types.ObjectId[]; observedImpact: { categories: string[]; summary: string }; observedResources: Types.ObjectId[]; observedMetrics: MetricObservation[]; observedEvents: Array<{ name: string; status?: string; source: string }>; observedFailures: Array<{ name: string; severity: ObservedSeverity; source: string }>; status: ObservationStatus; createdAt: Date; updatedAt: Date; }
const schema = new Schema<ObservedImpactDocument>({ changeId: { type: Schema.Types.ObjectId, ref: 'Change', required: true }, predictionId: { type: Schema.Types.ObjectId, ref: 'PredictionSnapshot', required: true }, resourceId: { type: Schema.Types.ObjectId, ref: 'Resource', required: true }, observationWindow: { start: Date, end: Date }, evidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }], observedImpact: { categories: [String], summary: String }, observedResources: [{ type: Schema.Types.ObjectId, ref: 'Resource' }], observedMetrics: [{ _id: false, name: String, baseline: Number, observed: Number, delta: Number, unit: String, direction: String, source: String }], observedEvents: [{ _id: false, name: String, status: String, source: String }], observedFailures: [{ _id: false, name: String, severity: String, source: String }], status: { type: String, enum: ['pending', 'observed', 'insufficient_evidence'], required: true } }, { timestamps: true });
schema.index({ changeId: 1, createdAt: -1 });
export type ObservedImpactDocumentHydrated = HydratedDocument<ObservedImpactDocument>;
export const ObservedImpactModel = model<ObservedImpactDocument>('ObservedImpact', schema);
export function toObservedImpactDTO(doc: ObservedImpactDocumentHydrated): ObservedImpactDTO { return { id: doc._id.toString(), changeId: doc.changeId.toString(), predictionId: doc.predictionId.toString(), resourceId: doc.resourceId.toString(), observationWindow: { start: doc.observationWindow.start.toISOString(), end: doc.observationWindow.end.toISOString() }, evidenceIds: doc.evidenceIds.map((id) => id.toString()), observedImpact: doc.observedImpact, observedResources: doc.observedResources.map((id) => id.toString()), observedMetrics: doc.observedMetrics, observedEvents: doc.observedEvents, observedFailures: doc.observedFailures, status: doc.status, createdAt: doc.createdAt.toISOString(), updatedAt: doc.updatedAt.toISOString() }; }