import { Schema, Types, model, type HydratedDocument } from 'mongoose';
import { sanitizeObject } from '../utils/sensitive-data.js';
import type { PredictionSnapshotDTO } from '../types/predictionReality.js';

export interface PredictionSnapshotDocument { changeId: Types.ObjectId; analysisId: Types.ObjectId; resourceId: Types.ObjectId; predictedAt: Date; predictedRisk: { score: number; level: string }; predictedImpact: { categories: string[]; summary: string }; predictedBlastRadius: { directCount: number; transitiveCount: number; totalCount: number; maxDependencyDepth: number }; predictedResourceIds: Types.ObjectId[]; predictedSecurityFindings: Array<{ fingerprint: string; findingId?: string; category: string; severity: string; title: string; evidenceIds: Types.ObjectId[] }>; predictionVersion: string; metadata: Record<string, unknown>; createdAt: Date; updatedAt: Date; }
const schema = new Schema<PredictionSnapshotDocument>({ changeId: { type: Schema.Types.ObjectId, ref: 'Change', required: true }, analysisId: { type: Schema.Types.ObjectId, ref: 'ChangeAnalysis', required: true }, resourceId: { type: Schema.Types.ObjectId, ref: 'Resource', required: true }, predictedAt: { type: Date, required: true }, predictedRisk: { score: Number, level: String }, predictedImpact: { categories: [String], summary: String }, predictedBlastRadius: { directCount: Number, transitiveCount: Number, totalCount: Number, maxDependencyDepth: Number }, predictedResourceIds: [{ type: Schema.Types.ObjectId, ref: 'Resource' }], predictedSecurityFindings: [{ _id: false, fingerprint: String, findingId: String, category: String, severity: String, title: String, evidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }] }], predictionVersion: { type: String, required: true }, metadata: { type: Schema.Types.Mixed, default: {} } }, { timestamps: true });
schema.index({ changeId: 1, predictedAt: -1 });
export type PredictionSnapshotDocumentHydrated = HydratedDocument<PredictionSnapshotDocument>;
export const PredictionSnapshotModel = model<PredictionSnapshotDocument>('PredictionSnapshot', schema);
export function toPredictionSnapshotDTO(doc: PredictionSnapshotDocumentHydrated): PredictionSnapshotDTO { return { id: doc._id.toString(), changeId: doc.changeId.toString(), analysisId: doc.analysisId.toString(), resourceId: doc.resourceId.toString(), predictedAt: doc.predictedAt.toISOString(), predictedRisk: doc.predictedRisk, predictedImpact: doc.predictedImpact, predictedBlastRadius: doc.predictedBlastRadius, predictedResourceIds: doc.predictedResourceIds.map((id) => id.toString()), predictedSecurityFindings: (doc.predictedSecurityFindings ?? []).map((finding) => ({ ...finding, evidenceIds: finding.evidenceIds.map((id) => id.toString()) })), predictionVersion: doc.predictionVersion, metadata: sanitizeObject(doc.metadata), createdAt: doc.createdAt.toISOString(), updatedAt: doc.updatedAt.toISOString() }; }