import { Schema, Types, model, type HydratedDocument } from 'mongoose';
import { sanitizeObject } from '../utils/sensitive-data.js';
import type { AuditEvent, ApprovalRecord, ExecutionResult, RemediationAction, RemediationDTO, RemediationRisk, RemediationStatus, RemediationType, RollbackPlan, PRStatus, ValidationResult, VerificationResult } from '../remediation/remediation.types.js';

export interface RemediationDocument { changeId: Types.ObjectId; resourceId: Types.ObjectId; affectedResourceIds: Types.ObjectId[]; blastRadius: { directCount: number; transitiveCount: number; totalCount: number; maxDependencyDepth: number }; investigationId?: Types.ObjectId; securityFindingIds: Types.ObjectId[]; predictionId?: Types.ObjectId; type: RemediationType; title: string; description: string; reason: string; proposedChanges: RemediationAction[]; validation?: ValidationResult; risk: RemediationRisk; status: RemediationStatus; approval?: ApprovalRecord; execution?: ExecutionResult; verification?: VerificationResult; rollback: RollbackPlan; evidenceIds: Types.ObjectId[]; createdBy: string; prStatus: PRStatus; prProposal?: Record<string, unknown>; audit: AuditEvent[]; metadata: Record<string, unknown>; createdAt: Date; updatedAt: Date; }
const schema = new Schema<RemediationDocument>({
  changeId: { type: Schema.Types.ObjectId, ref: 'Change', required: true }, resourceId: { type: Schema.Types.ObjectId, ref: 'Resource', required: true }, affectedResourceIds: [{ type: Schema.Types.ObjectId, ref: 'Resource' }], blastRadius: { directCount: Number, transitiveCount: Number, totalCount: Number, maxDependencyDepth: Number }, investigationId: { type: Schema.Types.ObjectId, ref: 'Investigation' }, securityFindingIds: [{ type: Schema.Types.ObjectId, ref: 'SecurityFinding' }], predictionId: { type: Schema.Types.ObjectId, ref: 'PredictionSnapshot' }, type: { type: String, enum: ['configuration', 'kubernetes', 'terraform', 'dependency', 'security', 'rollback', 'deployment', 'observability', 'unknown'], required: true }, title: { type: String, required: true, trim: true, maxlength: 240 }, description: { type: String, required: true, trim: true, maxlength: 2000 }, reason: { type: String, required: true, trim: true, maxlength: 2000 }, proposedChanges: { type: Schema.Types.Mixed, required: true }, validation: { type: Schema.Types.Mixed }, risk: { type: Schema.Types.Mixed, required: true }, status: { type: String, enum: ['proposed', 'analyzed', 'generated', 'validation_failed', 'validated', 'pr_created', 'awaiting_approval', 'approved', 'rejected', 'executing', 'executed', 'verification_failed', 'verified', 'cancelled', 'failed', 'unknown'], required: true, default: 'proposed' }, approval: { type: Schema.Types.Mixed }, execution: { type: Schema.Types.Mixed }, verification: { type: Schema.Types.Mixed }, rollback: { type: Schema.Types.Mixed, required: true }, evidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }], createdBy: { type: String, required: true, trim: true, maxlength: 160 }, prStatus: { type: String, enum: ['not_created', 'prepared', 'created', 'unknown'], required: true, default: 'not_created' }, prProposal: { type: Schema.Types.Mixed }, audit: { type: Schema.Types.Mixed, default: [] }, metadata: { type: Schema.Types.Mixed, default: {} }
}, { timestamps: true });
schema.index({ changeId: 1, createdAt: -1 }); schema.index({ resourceId: 1, createdAt: -1 }); schema.index({ status: 1, createdAt: -1 }); schema.index({ type: 1, createdAt: -1 });
export type RemediationHydratedDocument = HydratedDocument<RemediationDocument>;
export const RemediationModel = model<RemediationDocument>('Remediation', schema);
export function toRemediationDTO(document: RemediationHydratedDocument): RemediationDTO { return { id: document._id.toString(), changeId: document.changeId.toString(), resourceId: document.resourceId.toString(), affectedResourceIds: (document.affectedResourceIds ?? []).map((id) => id.toString()), blastRadius: document.blastRadius ?? { directCount: 0, transitiveCount: 0, totalCount: 1, maxDependencyDepth: 0 }, ...(document.investigationId ? { investigationId: document.investigationId.toString() } : {}), securityFindingIds: document.securityFindingIds.map((id) => id.toString()), ...(document.predictionId ? { predictionId: document.predictionId.toString() } : {}), type: document.type, title: document.title, description: document.description, reason: document.reason, proposedChanges: document.proposedChanges, validation: document.validation, risk: document.risk, status: document.status, approval: document.approval, execution: document.execution, verification: document.verification, rollback: document.rollback, evidenceIds: document.evidenceIds.map((id) => id.toString()), createdBy: document.createdBy, prStatus: document.prStatus, prProposal: document.prProposal ? sanitizeObject(document.prProposal) : undefined, audit: document.audit, metadata: sanitizeObject(document.metadata), createdAt: document.createdAt.toISOString(), updatedAt: document.updatedAt.toISOString() }; }