import { Schema, Types, model, type HydratedDocument } from 'mongoose';
import { sanitizeObject } from '../utils/sensitive-data.js';
import type { SecurityCategory, SecurityFinding, SecurityLocation, SecurityRemediation, SecuritySeverity, SecuritySource, SecurityStatus } from '../types/security.js';
export interface SecurityFindingDocument { resourceId?: Types.ObjectId; changeId?: Types.ObjectId; evidenceIds: Types.ObjectId[]; source: SecuritySource; category: SecurityCategory; severity: SecuritySeverity; title: string; description: string; ruleId?: string; cve?: string; cwe?: string; package?: string; installedVersion?: string; fixedVersion?: string; location?: SecurityLocation; status: SecurityStatus; confidence: number; remediation: SecurityRemediation; metadata: Record<string, unknown>; fingerprint: string; detectedAt: Date; createdAt: Date; updatedAt: Date; }
const securityFindingSchema = new Schema<SecurityFindingDocument>({ resourceId: { type: Schema.Types.ObjectId, ref: 'Resource' }, changeId: { type: Schema.Types.ObjectId, ref: 'Change' }, evidenceIds: [{ type: Schema.Types.ObjectId, ref: 'Evidence' }], source: { type: String, required: true, enum: ['scanner', 'configuration', 'dependency', 'container', 'terraform', 'kubernetes', 'code', 'ci_cd', 'manual'] }, category: { type: String, required: true, enum: ['vulnerability', 'misconfiguration', 'secret_exposure', 'dependency', 'container', 'iac', 'kubernetes', 'identity', 'network', 'ci_cd', 'configuration', 'unknown'] }, severity: { type: String, required: true, enum: ['info', 'low', 'medium', 'high', 'critical', 'unknown'], default: 'unknown' }, title: { type: String, required: true, trim: true, maxlength: 240 }, description: { type: String, required: true, trim: true, maxlength: 2000 }, ruleId: { type: String, trim: true, maxlength: 160 }, cve: { type: String, trim: true, maxlength: 80 }, cwe: { type: String, trim: true, maxlength: 80 }, package: { type: String, trim: true, maxlength: 200 }, installedVersion: { type: String, trim: true, maxlength: 80 }, fixedVersion: { type: String, trim: true, maxlength: 80 }, location: { type: Schema.Types.Mixed }, status: { type: String, required: true, enum: ['open', 'acknowledged', 'resolved', 'false_positive', 'unknown'], default: 'open' }, confidence: { type: Number, required: true, min: 0, max: 100 }, remediation: { type: Schema.Types.Mixed, required: true }, metadata: { type: Schema.Types.Mixed, default: {} }, fingerprint: { type: String, required: true }, detectedAt: { type: Date, required: true } }, { timestamps: true });
securityFindingSchema.index({ fingerprint: 1 }, { unique: true });
securityFindingSchema.index({ resourceId: 1 }); securityFindingSchema.index({ changeId: 1 }); securityFindingSchema.index({ severity: 1 }); securityFindingSchema.index({ category: 1 }); securityFindingSchema.index({ status: 1 }); securityFindingSchema.index({ detectedAt: -1 });
export type SecurityFindingHydratedDocument = HydratedDocument<SecurityFindingDocument>;
export const SecurityFindingModel = model<SecurityFindingDocument>('SecurityFinding', securityFindingSchema);
export function toSecurityFindingDTO(finding: SecurityFindingHydratedDocument): SecurityFinding { return { id: finding._id.toString(), ...(finding.resourceId ? { resourceId: finding.resourceId.toString() } : {}), ...(finding.changeId ? { changeId: finding.changeId.toString() } : {}), evidenceIds: finding.evidenceIds.map((id) => id.toString()), source: finding.source, category: finding.category, severity: finding.severity, title: finding.title, description: finding.description, ...(finding.ruleId ? { ruleId: finding.ruleId } : {}), ...(finding.cve ? { cve: finding.cve } : {}), ...(finding.cwe ? { cwe: finding.cwe } : {}), ...(finding.package ? { package: finding.package } : {}), ...(finding.installedVersion ? { installedVersion: finding.installedVersion } : {}), ...(finding.fixedVersion ? { fixedVersion: finding.fixedVersion } : {}), ...(finding.location ? { location: finding.location } : {}), status: finding.status, confidence: finding.confidence, remediation: finding.remediation, metadata: sanitizeObject(finding.metadata), fingerprint: finding.fingerprint, detectedAt: finding.detectedAt.toISOString(), createdAt: finding.createdAt.toISOString(), updatedAt: finding.updatedAt.toISOString() }; }