import type { AIAnalysisResult } from './types.js';
import { AppError } from '../utils/app-error.js';

const destructive = /delete|destroy|apply|deploy|rollback|kubectl|terraform|docker|shell|production/i;
export function validateAIResult(value: unknown, allowedEvidenceIds: Set<string>): AIAnalysisResult {
  if (typeof value !== 'object' || value === null) throw new AppError(502, 'AI response did not match the required structure.');
  const data = value as Record<string, unknown>; const stringField = (key: string) => { if (typeof data[key] !== 'string') throw new AppError(502, `AI response field ${key} is invalid.`); return data[key] as string; }; const confidence = (key: string, source: Record<string, unknown>) => { const result = source[key]; if (typeof result !== 'number' || result < 0 || result > 100) throw new AppError(502, 'AI response confidence must be between 0 and 100.'); return result; }; const refs = (value: unknown) => { if (!Array.isArray(value) || value.some((id) => typeof id !== 'string' || !allowedEvidenceIds.has(id))) throw new AppError(502, 'AI response referenced unavailable evidence.'); return [...new Set(value as string[])]; };
  if (!Array.isArray(data.hypotheses) || !Array.isArray(data.reasoning) || !Array.isArray(data.recommendations) || !Array.isArray(data.limitations)) throw new AppError(502, 'AI response arrays are invalid.');
  const root = data.rootCause; if (typeof root !== 'object' || root === null) throw new AppError(502, 'AI rootCause is invalid.'); const rootRecord = root as Record<string, unknown>;
  return { summary: stringField('summary'), rootCause: { statement: typeof rootRecord.statement === 'string' ? rootRecord.statement : 'Insufficient evidence to determine root cause.', confidence: confidence('confidence', rootRecord), evidenceIds: refs(rootRecord.evidenceIds) }, hypotheses: data.hypotheses.map((item) => { if (typeof item !== 'object' || item === null) throw new AppError(502, 'AI hypothesis is invalid.'); const record = item as Record<string, unknown>; return { title: typeof record.title === 'string' ? record.title : 'Untitled hypothesis', explanation: typeof record.explanation === 'string' ? record.explanation : 'Insufficient evidence.', confidence: confidence('confidence', record), supportingEvidenceIds: refs(record.supportingEvidenceIds), contradictingEvidenceIds: refs(record.contradictingEvidenceIds) }; }), evidenceReferences: refs(data.evidenceReferences), reasoning: data.reasoning.map((item) => { if (typeof item !== 'object' || item === null) throw new AppError(502, 'AI reasoning is invalid.'); const record = item as Record<string, unknown>; if (record.type !== 'fact' && record.type !== 'inference' && record.type !== 'hypothesis') throw new AppError(502, 'AI reasoning type is invalid.'); return { statement: typeof record.statement === 'string' ? record.statement : 'Insufficient evidence.', type: record.type }; }), impactExplanation: stringField('impactExplanation'), predictionRealityExplanation: stringField('predictionRealityExplanation'), recommendations: data.recommendations.map((item) => { if (typeof item !== 'object' || item === null) throw new AppError(502, 'AI recommendation is invalid.'); const record = item as Record<string, unknown>; const explanation = typeof record.explanation === 'string' ? record.explanation : 'Human approval required.'; return { title: typeof record.title === 'string' ? record.title : 'Recommendation', explanation, priority: typeof record.priority === 'string' ? record.priority : 'low', safe: destructive.test(explanation) ? false : record.safe === true, supportingEvidenceIds: refs(record.supportingEvidenceIds) }; }), limitations: data.limitations.filter((item): item is string => typeof item === 'string').slice(0, 20) };
}