import { createHmac, randomBytes, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { UserModel, toUserDTO, type UserRole } from '../models/User.js';
import { env } from '../config/env.js';
import { AppError } from '../utils/app-error.js';

const scrypt = promisify(scryptCallback); const TOKEN_TTL_SECONDS = 8 * 60 * 60;
async function hashPassword(password: string): Promise<string> { const salt = randomBytes(16).toString('hex'); const derived = await scrypt(password, salt, 64) as Buffer; return `${salt}:${derived.toString('hex')}`; }
async function verifyPassword(password: string, stored: string): Promise<boolean> { const [salt, hash] = stored.split(':'); if (!salt || !hash) return false; const derived = await scrypt(password, salt, 64) as Buffer; const expected = Buffer.from(hash, 'hex'); return expected.length === derived.length && timingSafeEqual(expected, derived); }
function tokenFor(user: { id: string; email: string; role: UserRole }): string { const payload = Buffer.from(JSON.stringify({ sub: user.id, email: user.email, role: user.role, exp: Math.floor(Date.now() / 1000) + TOKEN_TTL_SECONDS })).toString('base64url'); const signature = createHmac('sha256', env.jwtSecret).update(payload).digest('base64url'); return `${payload}.${signature}`; }
export function verifyToken(token: string): { id: string; email: string; role: UserRole } { const [payload, signature] = token.split('.'); if (!payload || !signature) throw new AppError(401, 'Authentication token is invalid.', 'AUTH_INVALID'); const expected = createHmac('sha256', env.jwtSecret).update(payload).digest('base64url'); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) throw new AppError(401, 'Authentication token is invalid.', 'AUTH_INVALID'); let data: { sub?: string; email?: string; role?: UserRole; exp?: number }; try { data = JSON.parse(Buffer.from(payload, 'base64url').toString()) as typeof data; } catch { throw new AppError(401, 'Authentication token is invalid.', 'AUTH_INVALID'); } if (!data.sub || !data.email || !data.role || !data.exp || data.exp < Math.floor(Date.now() / 1000)) throw new AppError(401, 'Authentication token is expired or invalid.', 'AUTH_EXPIRED'); return { id: data.sub, email: data.email, role: data.role }; }
export async function registerUser(email: string, password: string, requestedRole?: UserRole) { const normalized = email.trim().toLowerCase(); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized)) throw new AppError(400, 'Email is invalid.', 'AUTH_INVALID_EMAIL'); if (password.length < 12) throw new AppError(400, 'Password must be at least 12 characters.', 'AUTH_WEAK_PASSWORD'); const count = await UserModel.countDocuments(); if (count > 0 && !env.allowPublicRegistration) throw new AppError(403, 'Registration is disabled.', 'AUTH_REGISTRATION_DISABLED'); const role: UserRole = count === 0 ? 'admin' : requestedRole === 'operator' ? 'operator' : 'viewer'; try { const user = await UserModel.create({ email: normalized, passwordHash: await hashPassword(password), role, active: true }); return { user: toUserDTO(user), token: tokenFor({ id: user._id.toString(), email: user.email, role: user.role }) }; } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && error.code === 11000) throw new AppError(409, 'An account with this email already exists.', 'AUTH_DUPLICATE_EMAIL'); throw error; } }
export async function loginUser(email: string, password: string) { const user = await UserModel.findOne({ email: email.trim().toLowerCase(), active: true }); if (!user || !(await verifyPassword(password, user.passwordHash))) throw new AppError(401, 'Invalid credentials.', 'AUTH_INVALID_CREDENTIALS'); return { user: toUserDTO(user), token: tokenFor({ id: user._id.toString(), email: user.email, role: user.role }) }; }
export async function getUser(id: string) { const user = await UserModel.findById(id); if (!user || !user.active) throw new AppError(401, 'User is not available.', 'AUTH_USER_UNAVAILABLE'); return toUserDTO(user); }
export async function ensureInitialAdmin(): Promise<void> { if (!env.initialAdminEmail && !env.initialAdminPassword) return; if (!env.initialAdminEmail || !env.initialAdminPassword) throw new Error('INITIAL_ADMIN_EMAIL and INITIAL_ADMIN_PASSWORD must be provided together.'); if (await UserModel.countDocuments() > 0) return; await UserModel.create({ email: env.initialAdminEmail.toLowerCase(), passwordHash: await hashPassword(env.initialAdminPassword), role: 'admin', active: true }); }