import mongoose, { Types } from 'mongoose';
import { ChangeModel } from '../models/Change.js';
import { EvidenceModel } from '../models/Evidence.js';
import { ResourceModel } from '../models/Resource.js';
import { SecurityFindingModel, toSecurityFindingDTO, type SecurityFindingHydratedDocument } from '../models/SecurityFinding.js';
import { calculateSecurityRiskContribution } from '../engines/securityRiskEngine.js';
import { normalizeSecurityEvidence, fingerprintFor } from './securityNormalizer.js';
import type { CreateSecurityFindingInput, SecurityFinding, SecurityFindingFilters, SecuritySummary } from '../types/security.js';
import type { PaginatedResult } from '../types/pagination.js';
import { AppError } from '../utils/app-error.js';
import { sanitizeObject } from '../utils/sensitive-data.js';

function objectId(value: string, field: string): Types.ObjectId { if (!mongoose.isValidObjectId(value)) throw new AppError(400, `${field} must be a valid MongoDB ObjectId.`); return new Types.ObjectId(value); }
async function existingId(value: string | undefined, field: string, model: typeof ResourceModel | typeof ChangeModel): Promise<Types.ObjectId | undefined> { if (!value) return undefined; const id = objectId(value, field); if (!(await model.exists({ _id: id }))) throw new AppError(404, `${field} reference was not found.`); return id; }
async function evidenceIds(values: string[] = []): Promise<Types.ObjectId[]> { const ids = [...new Set(values)].map((value) => objectId(value, 'evidenceIds')); if (ids.length !== await EvidenceModel.countDocuments({ _id: { $in: ids } })) throw new AppError(404, 'One or more evidence references were not found.'); return ids; }
function dto(document: SecurityFindingHydratedDocument): SecurityFinding { return toSecurityFindingDTO(document); }

export async function createSecurityFinding(input: CreateSecurityFindingInput): Promise<SecurityFinding> {
  const resourceId = await existingId(input.resourceId, 'resourceId', ResourceModel); const changeId = await existingId(input.changeId, 'changeId', ChangeModel); const refs = await evidenceIds(input.evidenceIds);
  if (!Number.isInteger(input.confidence ?? 60) || (input.confidence ?? 60) < 0 || (input.confidence ?? 60) > 100) throw new AppError(400, 'confidence must be an integer between 0 and 100.');
  const detectedAt = new Date(input.detectedAt); if (Number.isNaN(detectedAt.getTime())) throw new AppError(400, 'detectedAt must be a valid date.');
  const record = { ...input, ...(resourceId ? { resourceId } : {}), ...(changeId ? { changeId } : {}), evidenceIds: refs, confidence: input.confidence ?? 60, severity: input.severity ?? 'unknown', status: input.status ?? 'open', remediation: input.remediation ?? { available: false }, metadata: sanitizeObject(input.metadata ?? {}), fingerprint: fingerprintFor(input), detectedAt };
  const saved = await SecurityFindingModel.findOneAndUpdate({ fingerprint: record.fingerprint }, { $setOnInsert: record }, { new: true, upsert: true, runValidators: true });
  return dto(saved as SecurityFindingHydratedDocument);
}

export async function listSecurityFindings(filters: SecurityFindingFilters, page: number, limit: number): Promise<PaginatedResult<SecurityFinding>> { const query: Record<string, unknown> = {}; for (const key of ['severity', 'category', 'status', 'source'] as const) if (filters[key]) query[key] = filters[key]; if (filters.resourceId) query.resourceId = objectId(filters.resourceId, 'resourceId'); if (filters.changeId) query.changeId = objectId(filters.changeId, 'changeId'); const [records, total] = await Promise.all([SecurityFindingModel.find(query).sort({ detectedAt: -1 }).skip((page - 1) * limit).limit(limit), SecurityFindingModel.countDocuments(query)]); return { data: records.map((record) => dto(record as SecurityFindingHydratedDocument)), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }; }
export async function getSecurityFinding(id: string): Promise<SecurityFinding> { const record = await SecurityFindingModel.findById(objectId(id, 'findingId')); if (!record) throw new AppError(404, 'Security finding not found.'); return dto(record as SecurityFindingHydratedDocument); }
export async function updateSecurityFinding(id: string, input: Partial<Pick<CreateSecurityFindingInput, 'status' | 'metadata' | 'remediation'>>): Promise<SecurityFinding> { const record = await SecurityFindingModel.findByIdAndUpdate(objectId(id, 'findingId'), { ...(input.status !== undefined ? { status: input.status } : {}), ...(input.remediation !== undefined ? { remediation: input.remediation } : {}), ...(input.metadata !== undefined ? { metadata: sanitizeObject(input.metadata) } : {}) }, { new: true, runValidators: true }); if (!record) throw new AppError(404, 'Security finding not found.'); return dto(record as SecurityFindingHydratedDocument); }
export async function deleteSecurityFinding(id: string): Promise<void> { if (!(await SecurityFindingModel.findByIdAndDelete(objectId(id, 'findingId')))) throw new AppError(404, 'Security finding not found.'); }
export async function getSecuritySummary(filters: SecurityFindingFilters = {}): Promise<SecuritySummary> { const result = await listSecurityFindings(filters, 1, 1000); const findings = result.data; const counts = { critical: 0, high: 0, medium: 0, low: 0, info: 0 }; findings.forEach((finding) => { if (finding.severity in counts) counts[finding.severity as keyof typeof counts] += 1; }); const highest = (['critical', 'high', 'medium', 'low', 'info', 'unknown'] as const).find((severity) => findings.some((finding) => finding.severity === severity)) ?? 'unknown'; return { total: findings.length, ...counts, open: findings.filter((finding) => finding.status === 'open').length, affectedResources: new Set(findings.map((finding) => finding.resourceId).filter(Boolean)).size, categories: Object.fromEntries([...new Set(findings.map((finding) => finding.category))].map((category) => [category, findings.filter((finding) => finding.category === category).length])), highestSeverity: highest, riskContribution: calculateSecurityRiskContribution(findings) }; }
export function getSecurityFindingsForChange(changeId: string, page: number, limit: number): Promise<PaginatedResult<SecurityFinding>> { return listSecurityFindings({ changeId }, page, limit); }
export function getSecurityFindingsForResource(resourceId: string, page: number, limit: number): Promise<PaginatedResult<SecurityFinding>> { return listSecurityFindings({ resourceId }, page, limit); }
export async function analyzeChangeSecurity(changeId: string): Promise<{ changeId: string; findings: SecurityFinding[]; summary: SecuritySummary }> { const changeObjectId = objectId(changeId, 'changeId'); const change = await ChangeModel.findById(changeObjectId); if (!change) throw new AppError(404, 'Change not found.'); const evidence = await EvidenceModel.find({ _id: { $in: change.evidenceIds } }).limit(100); const normalized = evidence.flatMap((record) => normalizeSecurityEvidence(record.payload, { resourceId: change.resourceId.toString(), changeId, evidenceIds: [record._id.toString()] })); const findings = await Promise.all(normalized.map((value) => createSecurityFinding(value))); return { changeId, findings, summary: await getSecuritySummary({ changeId }) }; }