import { describe, expect, it } from 'vitest';
import { calculatePredictionAccuracy, calculateRiskTrend, classifyOutcome, compareHistoricalFeatures, detectPredictionBias } from '../src/intelligence/intelligence.engine.js';
import type { HistoricalFeature } from '../src/intelligence/intelligence.types.js';

const base: HistoricalFeature = { changeId: 'old', resourceId: 'resource', resourceType: 'service', environment: 'production', changeType: 'configuration', riskScore: 60, riskLevel: 'high', changedItemCount: 2, impactCategories: ['configuration'], paths: ['replicas'], affectedResourceIds: ['resource'], dependencyResourceIds: ['database'], securityCategories: [], outcome: 'degraded', evidenceIds: ['evidence'], timestamp: '2026-01-01T00:00:00.000Z' };
describe('historical intelligence engine', () => {
  it('classifies missing evidence as insufficient and explicit rollback as reverted', () => { expect(classifyOutcome({ evidenceCount: 0 })).toBe('insufficient_evidence'); expect(classifyOutcome({ changeStatus: 'reverted', evidenceCount: 2 })).toBe('reverted'); expect(classifyOutcome({ verificationStatus: 'passed', evidenceCount: 1 })).toBe('successful'); });
  it('produces explainable similarity scores', () => { const result = compareHistoricalFeatures({ ...base, changeId: 'current' }, base); expect(result.similarityScore).toBeGreaterThan(80); expect(result.matchingFactors).toContain('same resource'); expect(result.evidenceIds).toEqual(['evidence']); });
  it('returns insufficient evidence for empty trends and deterministic rates for history', () => { expect(calculateRiskTrend([], 7).status).toBe('insufficient_evidence'); const result = calculateRiskTrend([base, { ...base, changeId: 'second', outcome: 'successful', riskLevel: 'medium', riskScore: 30 }], 30); expect(result.averageRiskScore).toBe(45); expect(result.sampleSize).toBe(2); });
  it('calculates accuracy and prediction bias without mutation', () => { expect(calculatePredictionAccuracy([]).status).toBe('insufficient_evidence'); expect(calculatePredictionAccuracy([{ accuracy: 80, level: 'good', evidenceIds: ['e'] }, { accuracy: null, level: 'insufficient_evidence', evidenceIds: [] }]).insufficientEvidenceRate).toBe(0.5); expect(detectPredictionBias([{ predictedScore: 20, observedSeverity: 'high', evidenceIds: ['e'] }, { predictedScore: 20, observedSeverity: 'high', evidenceIds: ['e2'] }]).type).toBe('underprediction'); });
});
